test_questions = {
    "en": {  # Английский
        "A1": [
            ("What's your name?", [["My name is John", "I am from London"], "Hello"]),
            ("How old are you?", [["I'm 20", "I'm 25"], "I like music"]),
            ("Where are you from?", [["I am from Paris", "I am from Italy"], "I like reading"]),
            ("What time is it?", [["It’s 3 o’clock", "It’s 5 o’clock"], "It’s raining"]),
            ("What is your favorite color?", [["My favorite color is blue", "I like red"], "I am a teacher"]),
            ("Do you like sports?", [["Yes, I like football", "Yes, I like tennis"], "I am 30 years old"]),
            ("Can you speak English?", [["Yes, I can", "I am learning English"], "I like ice cream"]),
            ("How are you?", [["I am fine, thank you", "I’m good, thanks"], "It’s 10 o’clock"]),
            ("What’s the weather like?", [["It’s sunny", "It’s hot"], "I’m hungry"]),
            ("What do you do?", [["I am a student", "I am a teacher"], "I like pizza"]),
        ],
        "A2": [
            ("What do you do in your free time?", [["I like playing basketball", "I like swimming"], "I am busy"]),
            ("Can you play the guitar?", [["Yes, I can play the guitar", "Yes, I play piano"], "I like sports"]),
            ("Where do you live?", [["I live in London", "I live in New York"], "I like reading books"]),
            ("How often do you go to the gym?", [["I go three times a week", "I go once a week"], "I’m cooking dinner"]),
            ("What did you do last weekend?", [["I visited my grandparents", "I went hiking"], "I am studying English"]),
            ("Do you like watching movies?", [["Yes, I love watching movies", "I like documentaries"], "I like to read books"]),
            ("Can you cook?", [["Yes, I can cook pasta", "Yes, I can make a sandwich"], "I am learning English"]),
            ("What’s your favorite food?", [["My favorite food is pizza", "I like sushi"], "I like swimming"]),
            ("How do you get to work?", [["I take the bus", "I walk to work"], "I have a cat"]),
            ("Where is your favorite place?", [["My favorite place is the beach", "I like the mountains"], "I like music"]),
        ],
        "B1": [
            ("What do you think about social media?", [["I think social media is useful", "It’s a good way to communicate"], "I like playing chess"]),
            ("How do you usually spend your holidays?", [["I usually visit new countries", "I go to the beach"], "I enjoy hiking"]),
            ("Can you describe your hometown?", [["My hometown is small and peaceful", "I love my hometown"], "I like reading"]),
            ("What are your career goals?", [["I want to become a software engineer", "I want to work as a doctor"], "I like traveling"]),
            ("Do you prefer reading books or watching movies?", [["I prefer reading books", "I like both reading books and watching movies"], "I am going to work"]),
            ("How important is education to you?", [["Education is very important to me", "I think education is the key to success"], "I like to read novels"]),
            ("Tell me about your last trip.", [["I went to Spain last summer", "I visited Italy last year"], "I like sports"]),
            ("How would you improve the environment?", [["I would reduce plastic use", "I would promote recycling"], "I am going to the beach"]),
            ("What’s your opinion on global warming?", [["It’s a serious problem", "It’s something we should address"], "I like swimming"]),
            ("What would you do if you won the lottery?", [["I would travel around the world", "I would donate to charity"], "I like singing"]),
        ]
    },
    "fr": {  # Французский
        "A1": [
            ("Comment tu t'appelles ?", [["Je m'appelle Jean", "Je suis de Paris"], "Salut"]),
            ("Quel âge as-tu ?", [["J'ai 20 ans", "J'ai 25 ans"], "J'aime la musique"]),
            ("D'où viens-tu ?", [["Je viens de Paris", "Je viens d'Italie"], "J'aime lire"]),
            ("Quelle heure est-il ?", [["Il est 3 heures", "Il est 5 heures"], "Il pleut"]),
            ("Quelle est ta couleur préférée ?", [["Ma couleur préférée est bleue", "J'aime le rouge"], "Je suis professeur"]),
            ("Aimes-tu le sport ?", [["Oui, j'aime le football", "Oui, j'aime le tennis"], "J'ai 30 ans"]),
            ("Parles-tu anglais ?", [["Oui, je parle anglais", "J'apprends l'anglais"], "J'aime la glace"]),
            ("Comment ça va ?", [["Ça va bien, merci", "Ça va, merci"], "Il est 10 heures"]),
            ("Quel temps fait-il ?", [["Il fait soleil", "Il fait chaud"], "J'ai faim"]),
            ("Que fais-tu ?", [["Je suis étudiant", "Je suis professeur"], "J'aime la pizza"]),
        ],
        "A2": [
            ("Que fais-tu pendant ton temps libre ?", [["J'aime jouer au basket", "J'aime nager"], "Je suis occupé"]),
            ("Sais-tu jouer de la guitare ?", [["Oui, je sais jouer de la guitare", "Oui, je joue du piano"], "J'aime le sport"]),
            ("Où habites-tu ?", [["J'habite à Paris", "J'habite à New York"], "J'aime lire des livres"]),
            ("À quelle fréquence vas-tu à la salle de sport ?", [["Je vais trois fois par semaine", "Je vais une fois par semaine"], "Je prépare le dîner"]),
            ("Que faisais-tu le week-end dernier ?", [["J'ai rendu visite à mes grands-parents", "Je suis allé en randonnée"], "J'étudie l'anglais"]),
            ("Aimes-tu regarder des films ?", [["Oui, j'adore regarder des films", "J'aime les documentaires"], "J'aime lire des livres"]),
            ("Sais-tu cuisiner ?", [["Oui, je sais cuisiner des pâtes", "Oui, je sais faire un sandwich"], "J'apprends l'anglais"]),
            ("Quel est ton plat préféré ?", [["Mon plat préféré est la pizza", "J'aime les sushis"], "J'aime nager"]),
            ("Comment vas-tu au travail ?", [["Je prends le bus", "Je vais à pied au travail"], "J'ai un chat"]),
            ("Quel est ton endroit préféré ?", [["Mon endroit préféré est la plage", "J'aime les montagnes"], "J'aime la musique"]),
        ],
        "B1": [
            ("Que penses-tu des réseaux sociaux ?", [["Je pense que les réseaux sociaux sont utiles", "C'est un bon moyen de communiquer"], "J'aime jouer aux échecs"]),
            ("Comment passes-tu généralement tes vacances ?", [["Je visite généralement de nouveaux pays", "Je vais à la plage"], "J'aime faire de la randonnée"]),
            ("Peux-tu décrire ta ville natale ?", [["Ma ville natale est petite et paisible", "J'aime ma ville natale"], "J'aime lire"]),
            ("Quels sont tes objectifs professionnels ?", [["Je veux devenir ingénieur en logiciel", "Je veux travailler comme médecin"], "J'aime voyager"]),
            ("Tu préfères lire des livres ou regarder des films ?", [["Je préfère lire des livres", "J'aime autant lire des livres que regarder des films"], "Je vais au travail"]),
            ("Quelle importance accordes-tu à l'éducation ?", [["L'éducation est très importante pour moi", "Je pense que l'éducation est la clé du succès"], "J'aime lire des romans"]),
            ("Parle-moi de ton dernier voyage.", [["Je suis allé en Espagne l'été dernier", "J'ai visité l'Italie l'année dernière"], "J'aime le sport"]),
            ("Comment améliorerais-tu l'environnement ?", [["Je réduirais l'utilisation du plastique", "Je favoriserais le recyclage"], "Je vais à la plage"]),
            ("Quelle est ton opinion sur le réchauffement climatique ?", [["C'est un problème sérieux", "C'est quelque chose auquel nous devons faire face"], "J'aime nager"]),
            ("Que ferais-tu si tu gagnais à la loterie ?", [["Je voyagerais autour du monde", "Je ferais des dons à des œuvres de charité"], "J'aime chanter"]),
        ]
    },
    "es": {  # Испанский
        "A1": [
            ("¿Cómo te llamas?", [["Me llamo Juan", "Soy de Madrid"], "Hola"]),
            ("¿Cuántos años tienes?", [["Tengo 20 años", "Tengo 25 años"], "Me gusta la música"]),
            ("¿De dónde eres?", [["Soy de París", "Soy de Italia"], "Me gusta leer"]),
            ("¿Qué hora es?", [["Son las 3 en punto", "Son las 5 en punto"], "Está lloviendo"]),
            ("¿Cuál es tu color favorito?", [["Mi color favorito es azul", "Me gusta el rojo"], "Soy profesor"]),
            ("¿Te gustan los deportes?", [["Sí, me gusta el fútbol", "Sí, me gusta el tenis"], "Tengo 30 años"]),
            ("¿Hablas inglés?", [["Sí, hablo inglés", "Estoy aprendiendo inglés"], "Me gusta el helado"]),
            ("¿Cómo estás?", [["Estoy bien, gracias", "Estoy bien, gracias"], "Son las 10 en punto"]),
            ("¿Qué tiempo hace?", [["Hace sol", "Hace calor"], "Tengo hambre"]),
            ("¿Qué haces?", [["Soy estudiante", "Soy profesor"], "Me gusta la pizza"]),
        ],
        "A2": [
            ("¿Qué haces en tu tiempo libre?", [["Me gusta jugar al baloncesto", "Me gusta nadar"], "Estoy ocupado"]),
            ("¿Sabes tocar la guitarra?", [["Sí, sé tocar la guitarra", "Sí, toco el piano"], "Me gusta el deporte"]),
            ("¿Dónde vives?", [["Vivo en Londres", "Vivo en Nueva York"], "Me gusta leer libros"]),
            ("¿Con qué frecuencia vas al gimnasio?", [["Voy tres veces por semana", "Voy una vez por semana"], "Estoy cocinando la cena"]),
            ("¿Qué hiciste el fin de semana pasado?", [["Visité a mis abuelos", "Fui de excursión"], "Estoy estudiando inglés"]),
            ("¿Te gusta ver películas?", [["Sí, me encanta ver películas", "Me gustan los documentales"], "Me gusta leer libros"]),
            ("¿Sabes cocinar?", [["Sí, sé cocinar pasta", "Sí, sé hacer un sándwich"], "Estoy aprendiendo inglés"]),
            ("¿Cuál es tu comida favorita?", [["Mi comida favorita es la pizza", "Me gusta el sushi"], "Me gusta nadar"]),
            ("¿Cómo vas al trabajo?", [["Voy en autobús", "Voy caminando al trabajo"], "Tengo un gato"]),
            ("¿Cuál es tu lugar favorito?", [["Mi lugar favorito es la playa", "Me gustan las montañas"], "Me gusta la música"]),
        ],
        "B1": [
            ("¿Qué piensas sobre las redes sociales?", [["Creo que las redes sociales son útiles", "Es una buena forma de comunicarse"], "Me gusta jugar al ajedrez"]),
            ("¿Cómo sueles pasar tus vacaciones?", [["Suelo visitar nuevos países", "Voy a la playa"], "Me gusta hacer senderismo"]),
            ("¿Puedes describir tu ciudad natal?", [["Mi ciudad natal es pequeña y tranquila", "Me encanta mi ciudad natal"], "Me gusta leer"]),
            ("¿Cuáles son tus objetivos profesionales?", [["Quiero ser ingeniero de software", "Quiero trabajar como médico"], "Me gusta viajar"]),
            ("¿Prefieres leer libros o ver películas?", [["Prefiero leer libros", "Me gusta tanto leer libros como ver películas"], "Voy al trabajo"]),
            ("¿Qué importancia tiene la educación para ti?", [["La educación es muy importante para mí", "Creo que la educación es la clave del éxito"], "Me gusta leer novelas"]),
            ("Cuéntame sobre tu último viaje.", [["Fui a España el verano pasado", "Visité Italia el año pasado"], "Me gusta el deporte"]),
            ("¿Cómo mejorarías el medio ambiente?", [["Reduciría el uso de plásticos", "Fomentaría el reciclaje"], "Voy a la playa"]),
            ("¿Cuál es tu opinión sobre el calentamiento global?", [["Es un problema serio", "Es algo que debemos abordar"], "Me gusta nadar"]),
            ("¿Qué harías si ganaras la lotería?", [["Viajaría por el mundo", "Donaría a la caridad"], "Me gusta cantar"]),
        ]
    },
    "it": {  # Итальянский
        "A1": [
            ("Come ti chiami?", [["Mi chiamo Giovanni", "Vengo da Roma"], "Ciao"]),
            ("Quanti anni hai?", [["Ho 20 anni", "Ho 25 anni"], "Mi piace la musica"]),
            ("Da dove vieni?", [["Vengo da Parigi", "Vengo dall'Italia"], "Mi piace leggere"]),
            ("Che ore sono?", [["Sono le 3", "Sono le 5"], "Piove"]),
            ("Qual è il tuo colore preferito?", [["Il mio colore preferito è il blu", "Mi piace il rosso"], "Sono insegnante"]),
            ("Ti piacciono gli sport?", [["Sì, mi piace il calcio", "Sì, mi piace il tennis"], "Ho 30 anni"]),
            ("Parli inglese?", [["Sì, parlo inglese", "Sto imparando l'inglese"], "Mi piace il gelato"]),
            ("Come stai?", [["Sto bene, grazie", "Sto bene, grazie"], "Sono le 10"]),
            ("Che tempo fa?", [["C'è il sole", "Fa caldo"], "Ho fame"]),
            ("Cosa fai?", [["Sono uno studente", "Sono un insegnante"], "Mi piace la pizza"]),
        ],
        "A2": [
            ("Cosa fai nel tuo tempo libero?", [["Mi piace giocare a basket", "Mi piace nuotare"], "Sono occupato"]),
            ("Sai suonare la chitarra?", [["Sì, so suonare la chitarra", "Sì, suono il pianoforte"], "Mi piace lo sport"]),
            ("Dove vivi?", [["Vivo a Londra", "Vivo a New York"], "Mi piace leggere libri"]),
            ("Quanto spesso vai in palestra?", [["Vado tre volte a settimana", "Vado una volta a settimana"], "Sto cucinando la cena"]),
            ("Cosa hai fatto lo scorso fine settimana?", [["Ho visitato i miei nonni", "Sono andato a fare un'escursione"], "Sto studiando l'inglese"]),
            ("Ti piace guardare film?", [["Sì, adoro guardare film", "Mi piacciono i documentari"], "Mi piace leggere libri"]),
            ("Sai cucinare?", [["Sì, so cucinare la pasta", "Sì, so fare un panino"], "Sto imparando l'inglese"]),
            ("Qual è il tuo cibo preferito?", [["Il mio cibo preferito è la pizza", "Mi piacciono i sushi"], "Mi piace nuotare"]),
            ("Come vai al lavoro?", [["Prendo l'autobus", "Vado al lavoro a piedi"], "Ho un gatto"]),
            ("Qual è il tuo posto preferito?", [["Il mio posto preferito è la spiaggia", "Mi piacciono le montagne"], "Mi piace la musica"]),
        ],
        "B1": [
            ("Cosa pensi dei social media?", [["Penso che i social media siano utili", "È un buon modo per comunicare"], "Mi piace giocare a scacchi"]),
            ("Come passi di solito le tue vacanze?", [["Di solito visito nuovi paesi", "Vado in spiaggia"], "Mi piace fare escursioni"]),
            ("Puoi descrivere la tua città natale?", [["La mia città natale è piccola e tranquilla", "Adoro la mia città natale"], "Mi piace leggere"]),
            ("Quali sono i tuoi obiettivi professionali?", [["Voglio diventare un ingegnere del software", "Voglio lavorare come medico"], "Mi piace viaggiare"]),
            ("Preferisci leggere libri o guardare film?", [["Preferisco leggere libri", "Mi piace sia leggere libri che guardare film"], "Vado al lavoro"]),
            ("Quanto è importante l'educazione per te?", [["L'educazione è molto importante per me", "Penso che l'educazione sia la chiave per il successo"], "Mi piace leggere romanzi"]),
            ("Parlami del tuo ultimo viaggio.", [["Sono andato in Spagna l'estate scorsa", "Ho visitato l'Italia l'anno scorso"], "Mi piace lo sport"]),
            ("Come miglioreresti l'ambiente?", [["Ridurrei l'uso della plastica", "Promuoverei il riciclo"], "Vado in spiaggia"]),
            ("Qual è la tua opinione sul riscaldamento globale?", [["È un problema serio", "È qualcosa di cui dobbiamo occuparci"], "Mi piace nuotare"]),
            ("Cosa faresti se vincessi alla lotteria?", [["Viaggerei per il mondo", "Farebbe donazioni a beneficenza"], "Mi piace cantare"]),
        ]
    }
}
